### ISSUE TITLE
Link in Code

### ISSUE THREAD

**Issue by DaveyRance** [TooTall18T/tool_length_probe#1]
Good morning.

I have been using this probing routine and it is working great. A suggestion that you may want to consider is to put your github il the .ngc files as that way when someone comes to look at the files they can find a link back to the wonderful work that you did.

This also makes sure that you get credit like you gave for the original touch off routine.

(For my copy of the files i added in just under the version number)

;https://github.com/TooTall18T/tool_length_probe

**Comment by TooTall18T** [comment]
Glad to hear it works and thanks for the tip.
When I finally do the next update I will take it into account.
